config/routes.rb
Hatstore::Application.routes.draw do
  devise_for :admin_users, :path => "admin", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  root to: 'admin/xml#index'
  namespace :admin do
      resources :xml, only: [:index]
          resources :produtos do
            post 'create_or_update_produtos', on: :collection
          end
          resources :xml
  end
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/produto.rb
class Admin::Produto < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/xml.rb
class Admin::Xml < ActiveRecord::Base
  
end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < ApplicationController
  before_action :set_admin_produto, only: [:show, :edit, :update, :destroy]

  # GET /admin/produtos
  # GET /admin/produtos.json
  def index
    @admin_produtos = Admin::Produto.all
  end

  # GET /admin/produtos/1
  # GET /admin/produtos/1.json
  def show
  end

  # GET /admin/produtos/new
  def new
    @admin_produto = Admin::Produto.new
  end

  def create_or_update_produtos
    params[:admin_produto][:produto].each.with_index(0) do |a,index|
        if a[1]["exists"] != nil
          @create_or_update = Admin::Produto.find_by_code(a[1]["codigo"])
          if @create_or_update.nil?
            @admin_produto = Admin::Produto.create(name: a[1]["name"], code: a[1]["codigo"], price: a[1]["preco"], url: a[1]["url"], nparcela: a[1]["nparcela"], vparcela: a[1]["vparcela"], marca: a[1]["marca"])          
          else
            @admin_produto = @create_or_update.update(name: a[1]["name"], code: a[1]["codigo"], price: a[1]["preco"], url: a[1]["url"], nparcela: a[1]["nparcela"], vparcela: a[1]["vparcela"], marca: a[1]["marca"])          
          end        
        end
    end
    redirect_to :root
    
  end
  # GET /admin/produtos/1/edit
  def edit
  end

  # POST /admin/produtos
  # POST /admin/produtos.json
  def create
    @admin_produto = Admin::Produto.new(admin_produto_params)

    respond_to do |format|
      if @admin_produto.save
        format.html { redirect_to @admin_produto, notice: 'Produto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_produto }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/produtos/1
  # PATCH/PUT /admin/produtos/1.json
  def update
    respond_to do |format|
      if @admin_produto.update(admin_produto_params)
        format.html { redirect_to @admin_produto, notice: 'Produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/produtos/1
  # DELETE /admin/produtos/1.json
  def destroy
    @admin_produto.destroy
    respond_to do |format|
      format.html { redirect_to admin_produtos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_produto
      @admin_produto = Admin::Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_produto_params
      params.require(:admin_produto).permit(:code, :name, :url, :price, :nparcela, :vparcela, :image, :marca)
    end
end

app/controllers/admin/xml_controller.rb
require 'open-uri'
class Admin::XmlController < ApplicationController
	def index
		@xml = Admin::Produto.new

		@array_produtos = Array.new
		produtos = Admin::Produto.all
		doc = Nokogiri::XML(open("http://www.hatstore.com.br/xml/8c1d9/shoppinguol.xml"))
		@doc = doc.xpath('//PRODUTOS/PRODUTO').each do |i|
			#i.xpath('DESCRICAO').children.text
			xml = Admin::Produto.find_by_code(i.xpath('CODIGO').children.text)
				if xml
					@array_produtos << { codigo: i.xpath("CODIGO").children.text, name: i.xpath("DESCRICAO").children.text, url: i.xpath("URL").children.text, preco: i.xpath("PRECO").children.text, nparcela: i.xpath("NParcela").children.text, vparcela: i.xpath("VParcela").children.text, image: i.xpath("URL_IMAGE").children.text, marca: i.xpath("DEPARTAMENTO").children.text , exists: '1'}
				else
					@array_produtos << { codigo: i.xpath("CODIGO").children.text, name: i.xpath("DESCRICAO").children.text, url: i.xpath("URL").children.text, preco: i.xpath("PRECO").children.text, nparcela: i.xpath("NParcela").children.text, vparcela: i.xpath("VParcela").children.text, image: i.xpath("URL_IMAGE").children.text, marca: i.xpath("DEPARTAMENTO").children.text, exists: '0' }
					
				end				
		end
	end

	def read_xml
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_admin_user!
  protect_from_forgery with: :exception
end

app/helpers/admin/produtos_helper.rb
module Admin::ProdutosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/xml_helper.rb
module XmlHelper

	def red_green
		
	end
end

app/views/admin/produtos/_form.html.erb
<%= form_for(@admin_produto) do |f| %>
  <% if @admin_produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_produto.errors.count, "error") %> prohibited this admin_produto from being saved:</h2>

      <ul>
      <% @admin_produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :nparcela %><br>
    <%= f.number_field :nparcela %>
  </div>
  <div class="field">
    <%= f.label :vparcela %><br>
    <%= f.text_field :vparcela %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/produtos/edit.html.erb
<h1>Editing admin_produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_produto %> |
<%= link_to 'Back', admin_produtos_path %>

app/views/admin/produtos/index.html.erb
<h1>Lista de Produtos</h1>

<p> Aqui lista todos os produtos dando a opção para deletar, criar e atualizar!<p>

<p><b>Você possui <%= @admin_produtos.count %> produtos ativos ativos</b></p>
<table class="table table-striped">
  <thead>
      <td>Name</td>
      <td>Codigo</td>      
      <td>Preco</td>
      <td>N Parcela</td>
      <td>V Parcela</td>
      <td>Imagem</td>

      <td>Marca</td>
  </thead>

  <tbody class="">
    <% @admin_produtos.each do |admin_produto| %>
      <tr>
        <td><%= admin_produto.code %></td>
        <td><%= admin_produto.name %></td>
        <td><%= admin_produto.price %></td>
        <td><%= admin_produto.nparcela %></td>
        <td><%= admin_produto.vparcela %></td>
        <td><a href="<%= admin_produto.image.url %>"><img src="<%= admin_produto.image.url %>" /></a></td>
        <td><%= admin_produto.marca %></td>
        <td><%= link_to 'Exibir', admin_produto %></td>
        <td><%= link_to 'Editar', edit_admin_produto_path(admin_produto) %></td>
        <td><%= link_to 'Deletar', admin_produto, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_admin_produto_path %>

app/views/admin/produtos/new.html.erb
<h1>New admin_produto</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_produtos_path %>

app/views/admin/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @admin_produto.code %>
</p>


<p>
  <strong>Name:</strong>
  <%= @admin_produto.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @admin_produto.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @admin_produto.price %>
</p>

<p>
  <strong>Nparcela:</strong>
  <%= @admin_produto.nparcela %>
</p>

<p>
  <strong>Vparcela:</strong>
  <%= @admin_produto.vparcela %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin_produto.image %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @admin_produto.marca %>
</p>


<%= link_to 'Edit', edit_admin_produto_path(@admin_produto) %> |
<%= link_to 'Back', admin_produtos_path %>

app/views/admin/xml/index.html.erb
<h2>
	Atualizar XML	
</h2>
<p>
	Para atualizar os produtos basta clicar no Cadastrar Produtos, com isso os produtos selecionados irão para a base
</p>

<div class="table-responsive">
	<table class="table">
		<thead>
			<td>Checked</td>
			<td>Name</td>
			<td>Codigo</td>
			<td>Preco</td>
			<td>Marca</td>

		</thead>
		<tbody>
			<%= form_for @xml, url: {action: "create_or_update_produtos", controller: "admin/produtos"}, html: {class: "nifty_form"} do |f| %>
				<% @array_produtos.map.with_index(0)  do |produto, index| %>		
					<% if produto[:exists] == '0' %>
							<tr class="tr-green">

								<td><input id="admin_produto_exists" name="admin_produto[produto][<%= index %>][exists]" type="checkbox" value="0" checked="checked"></td>
								<td><%= f.text_field :name, value: produto[:name],:name => "admin_produto[produto][#{index}][name]" %></td>			
								<td><%= f.text_field :codigo, value: produto[:codigo],:name => "admin_produto[produto][#{index}][codigo]" %></td>	
								<td><%= f.text_field :preco, value: produto[:preco],:name => "admin_produto[produto][#{index}][preco]" %></td>

								<td><%= f.text_field :marca, value: produto[:marca],:name => "admin_produto[produto][#{index}][marca]" %></td>

								<td><%= f.hidden_field :url, value: produto[:url],:name => "admin_produto[produto][#{index}][url]" %></td>	
								<td><%= f.hidden_field :nparcela, value: produto[:nparcela],:name => "admin_produto[produto][#{index}][nparcela]" %></td>	
								<td><%= f.hidden_field :vparcela, value: produto[:vparcela],:name => "admin_produto[produto][#{index}][vparcela]" %></td>		
							</tr>
					<% else %>
							<tr class="tr-red">
								<td><input id="admin_produto_exists" name="admin_produto[produto][<%= index %>][exists]" type="checkbox" value="0"></td>
								<td><%= f.text_field :name, value: produto[:name],:name => "admin_produto[produto][#{index}][name]" %></td>			
								<td><%= f.text_field :codigo, value: produto[:codigo],:name => "admin_produto[produto][#{index}][codigo]" %></td>	
								<td><%= f.text_field :preco, value: produto[:preco],:name => "admin_produto[produto][#{index}][preco]" %></td>
								<td><%= f.text_field :marca, value: produto[:marca],:name => "admin_produto[produto][#{index}][marca]" %></td>								
								<td><%= f.hidden_field :url, value: produto[:url],:name => "admin_produto[produto][#{index}][url]" %></td>	
								<td><%= f.hidden_field :nparcela, value: produto[:nparcela],:name => "admin_produto[produto][#{index}][nparcela]" %></td>	
								<td><%= f.hidden_field :vparcela, value: produto[:vparcela],:name => "admin_produto[produto][#{index}][vparcela]" %></td>	
								
							</tr>
					<% end %>
				<% end %>
				<div class="xml-button-fixed">
					<td>
					<input name="commit" type="submit" value="Create Produto">
					</td>
				</div>
				
		<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hatstore" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Hatstore Aplicativo</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Atualizar XML", "/"  %></li>
              <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      Produtos <span class="caret"></span>
              </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Lista Produtos", "/admin/produtos"  %></li>
                  <li></li>
                </ul>
              <li>
              
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <!-- div class="span3">
        </div><!/span--> 
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :nparcela %><br>
    <%= f.number_field :nparcela %>
  </div>
  <div class="field">
    <%= f.label :vparcela %><br>
    <%= f.text_field :vparcela %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>